---
# file: docker.yml
- hosts: docker
  become: true
  
  pre_tasks:
    - name: Update apt-cache if needed
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Add docker data group
      group:
        name: "{{ data_user }}"
        state: present
        gid: "{{ data_id }}"
    - name: Add docker data user
      user:
        name: "{{ data_user }}"
        state: present
        uid: "{{ data_id }}"
        group: "{{ data_user }}"
        append: yes
        groups:
          - "{{ data_user }}"
    
  roles:
    - base_server
    - docker
  
  tasks:
    - name: Docker macvlan network
      docker_network:
        name: lan-network
        driver: "macvlan"
        driver_options:
          parent: eth0
        ipam_config:
          - subnet: "192.168.0.0/24"
            gateway: "192.168.0.1"
            iprange: "192.168.0.64/26"
    - name: Install git
      apt:
        name:
          - git
        state: present
    - name: Add devops to "{{ data_user }}"
      user:
        name: devops
        state: present
        append: yes
        groups:
          - "{{ data_user }}"
    - name: Setup docker directories
      file:
        path: "{{item}}"
        state: directory
        mode: 0775
        owner: "{{ data_user }}"
        group: "{{ data_user }}"
      loop:
        - /ctr_cfg
        - /ctr_data
    - name: Checkout Docker configuration
      git:
        repo: git@github.com:acbgbca/microserver-docker.git
        dest: /ctr_cfg
        update: no
      register: gitupdate
    - name: Fix Git ownership
      file:
        path: /ctr_cfg
        state: directory
        mode: 0775
        owner: "{{ data_user }}"
        group: "{{ data_user }}"
        recursive: yes
      when: gitupdate.changed
    - name: Setup NFS backup directory
      file:
        path: "/mnt/backup"
        state: directory
    - name: Setup backup NFS mount
      lineinfile:
        path: /etc/fstab
        backup: yes
        search_string: '/mnt/backup'
        line: "192.168.0.201:/nfs/backup/docker        /mnt/backup     nfs     defaults        0 0"
        state: present
      notify: Mount backup

  handlers:
    - name: Mount backup
      ansible.posix.mount:
        path: /mnt/backup
        state: remounted