---
# file: docker.yml
- hosts: docker
  gather_facts: yes
  remote_user: devops
  become: true
  
  tasks:
    - name: Add devops user to the sudoers
      copy:
          dest: "/etc/sudoers.d/devops"
          content: "devops  ALL=(ALL)  NOPASSWD: ALL"
    - name: Deploy SSH Key
      authorized_key: user=devops
                     key="{{ lookup('file', 'authorized_sshkey.pub') }}"
                     state=present
    - name: Disable Password Authentication
      lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PasswordAuthentication'
           line="PasswordAuthentication no"
           state=present
           backup=yes
    - name: Disable Root Login
      lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin'
           line="PermitRootLogin no"
           state=present
           backup=yes
      notify:
        - restart ssh
    - name: Install Loki Plugin
      community.docker.docker_plugin:
        plugin_name: grafana/loki-docker-driver:latest
        alias: loki
        state: present
    - name: Enable Loki Plugin
      community.docker.docker_plugin:
        plugin_name: grafana/loki-docker-driver:latest
        alias: loki
        state: enable
    - name: Setup Docker Daemon configuration
      ansible.builtin.copy:
        src: daemon.json
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: u+rw,g+rw
    - name: NFS Video mount
      docker_volume:
        driver: "local"
        driver_options:
          type: nfs
          o: "addr=192.168.0.201,rw"
          device: :/nfs/videos
        volume_name: videos
    - name: NFS downloads mount
      docker_volume:
        driver: "local"
        driver_options:
          type: nfs
          o: "addr=192.168.0.201,rw"
          device: :/nfs/downloads
        volume_name: downloads
    - name: NFS pictures mount
      docker_volume:
        driver: "local"
        driver_options:
          type: nfs
          o: "addr=192.168.0.201,rw"
          device: :/nfs/pictures
        volume_name: pictures
    - name: NFS music mount
      docker_volume:
        driver: "local"
        driver_options:
          type: nfs
          o: "addr=192.168.0.201,rw"
          device: :/nfs/music
        volume_name: music
    - name: Setup automatic updates
      import_tasks: shared_tasks/auto-updates.yml

  handlers:
    - name: restart ssh
      service:
        name=sshd
        state=restarted