---
# file: docker.yml
- hosts: docker
  gather_facts: yes
  remote_user: devops
  become: true
  
  tasks:
    - name: Add devops user to the sudoers
      copy:
          dest: "/etc/sudoers.d/devops"
          content: "devops  ALL=(ALL)  NOPASSWD: ALL"
    - name: Deploy SSH Key
      authorized_key: user=devops
                     key="{{ lookup('file', 'authorized_sshkey.pub') }}"
                     state=present
    - name: Disable Password Authentication
      lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PasswordAuthentication'
           line="PasswordAuthentication no"
           state=present
           backup=yes
    - name: Disable Root Login
      lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin'
           line="PermitRootLogin no"
           state=present
           backup=yes
      notify:
        - restart ssh
    - name: Install Loki Plugin
      community.docker.docker_plugin:
        plugin_name: grafana/loki-docker-driver:latest
        alias: loki
        state: present
    - name: Enable Loki Plugin
      community.docker.docker_plugin:
        plugin_name: grafana/loki-docker-driver:latest
        alias: loki
        state: enable
    - name: Setup mDNS domains
      ansible.builtin.systemd:
        name: avahi-subdomain@{{ item }}.local.service
        state: started
        enabled: yes
      loop:
        - gitea
        - nexus
        - nexusdocker
        - woodpecker
        - dockerregistry
    - name: Update Avahi configuration
      lineinfile:
           dest=/etc/avahi/avahi-daemon.conf
           regexp='^#?enable-reflector='
           line="enable-reflector=yes"
           state=present
           backup=yes
    - name: Setup Docker Daemon configuration
      ansible.builtin.copy:
        src: daemon.json
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: u+rw,g+rw
    - name: Setup automatic updates
      import_tasks: shared_tasks/auto-updates.yml

  handlers:
    - name: restart ssh
      service:
        name=sshd
        state=restarted