---
# file: docker.yml
- hosts: kasm
  gather_facts: yes
  remote_user: devops
  become: true
  
  tasks:
    - name: Add devops user to the sudoers
      copy:
          dest: "/etc/sudoers.d/devops"
          content: "devops  ALL=(ALL)  NOPASSWD: ALL"
    - name: Deploy SSH Key
      authorized_key: user=devops
                     key="{{ lookup('file', 'authorized_sshkey.pub') }}"
                     state=present
    - name: Disable Password Authentication
      lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PasswordAuthentication'
           line="PasswordAuthentication no"
           state=present
           backup=yes
    - name: Disable Root Login
      lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin'
           line="PermitRootLogin no"
           state=present
           backup=yes
      notify:
        - restart ssh
    - name: install mDNS
      apt:
        pkg:
        - avahi-daemon
        - avahi-utils
      notify:
        - restart avahi
    - name: Setup automatic updates
      import_tasks: shared_tasks/auto-updates.yml
  handlers:
    - name: restart ssh
      service:
        name=sshd
        state=restarted
    - name: restart avahi
      service:
        name=avahi-daemon
        state=restarted