---
# file: proxmox.yml
- hosts: proxmox
  gather_facts: yes
  remote_user: devops
  become: true

  roles:
    - base_server
    - role: nfs_server
      tags: nfs
    - role: cloud_sync
      tags: cloudsync
  
  tasks:
    - name: Remove Proxmox Enterprise Repository
      lineinfile:
           dest=/etc/apt/sources.list.d/pve-enterprise.list
           regexp='^deb https://enterprise.proxmox.com/debian/pve'
           line="# deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise"
           state=present
           backup=yes
    - name: Add Proxmox No-Sub Repository
      lineinfile:
           dest=/etc/apt/sources.list.d/pve-enterprise.list
           line="deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription"
           state=present
           backup=yes