---
# file: proxmox.yml
- hosts: proxmox
  gather_facts: yes
  remote_user: devops
  become: true
  
  tasks:
    - name: Add devops user to the sudoers
      copy:
          dest: "/etc/sudoers.d/devops"
          content: "devops  ALL=(ALL)  NOPASSWD: ALL"
    - name: Deploy SSH Key
      authorized_key: user=devops
                     key="{{ lookup('file', 'authorized_sshkey.pub') }}"
                     state=present
    - name: Disable Password Authentication
      lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PasswordAuthentication'
           line="PasswordAuthentication no"
           state=present
           backup=yes
    - name: Disable Root Login
      lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin'
           line="PermitRootLogin no"
           state=present
           backup=yes
      notify:
        - restart ssh
    - name: Remove Proxmox Enterprise Repository
      lineinfile:
           dest=/etc/apt/sources.list.d/pve-enterprise.list
           regexp='^deb https://enterprise.proxmox.com/debian/pve'
           line="# deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise"
           state=present
           backup=yes
    - name: Add Proxmox No-Sub Repository
      lineinfile:
           dest=/etc/apt/sources.list.d/pve-enterprise.list
           line="deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription"
           state=present
           backup=yes
    - name: install Node Exporter
      apt:
        pkg:
        - prometheus-node-exporter
    - name: Setup automatic updates
      import_tasks: shared_tasks/auto-updates.yml
  handlers:
    - name: restart ssh
      service:
        name=sshd
        state=restarted