---
# file: proxmox.yml
- hosts: proxmox
  gather_facts: yes
  remote_user: devops
  become: true

  roles:
    - base_server
    - role: nfs_server
      tags: nfs
    - role: cloud_sync
      tags: cloudsync
  
  tasks:
    - name: Remove Proxmox Enterprise Repository
      lineinfile:
           dest=/etc/apt/sources.list.d/pve-enterprise.list
           regexp='^deb https://enterprise.proxmox.com/debian/pve'
           line="# deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise"
           state=present
           backup=yes
    - name: Add Proxmox No-Sub Repository
      lineinfile:
           dest=/etc/apt/sources.list.d/pve-enterprise.list
           line="deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription"
           state=present
           backup=yes
    - name: Setup script directory
      ansible.builtin.file:
        path: "/home/{{ cloud_sources.rclone_user }}/bin"
        state: directory
        owner: "{{  cloud_sources.rclone_user }}"
        group: "{{  cloud_sources.rclone_user }}"
        mode: 0775
      tags: paperless
    - name: Paperless Consume Script
      ansible.builtin.template:
        src: templates/paperless_consume.sh.j2
        dest: "/home/{{ cloud_sources.rclone_user }}/bin/paperless_consume.sh"
        owner: "{{  cloud_sources.rclone_user }}"
        group: "{{  cloud_sources.rclone_user }}"
        mode : 0775
      tags: paperless
    - name: Paperless Consume Cron
      ansible.builtin.cron:
        name: "Download Files for Paperless"
        minute: "*/15"
        job: "/home/{{ cloud_sources.rclone_user }}/bin/paperless_consume.sh >> /var/log/paperless"
        user: "{{  cloud_sources.rclone_user }}"
      tags: paperless
    - name: Image Sync Script
      ansible.builtin.template:
        src: templates/image_sync.sh.j2
        dest: "/home/{{ cloud_sources.rclone_user }}/bin/image_sync.sh"
        owner: "{{  cloud_sources.rclone_user }}"
        group: "{{  cloud_sources.rclone_user }}"
        mode : 0775
      tags: imagesync
    - name: Image Sync Cron
      ansible.builtin.cron:
        name: "Image Sync"
        minute: "15"
        hour: "5"
        job: "/home/{{ cloud_sources.rclone_user }}/bin/image_sync.sh >> /var/log/imagesync"
        user: "{{  cloud_sources.rclone_user }}"
      tags: imagesync
