---
# file: proxmox-firstrun.yml
- hosts: proxmox
  gather_facts: no
  remote_user: root

  pre_tasks:
    - name: install python
      raw: 'apt-get install python3'
      args:
        executable: /bin/bash
    - name: install sudo
      apt:
        name: sudo
        state: present
  
  roles:
  - base_server