---
# file: proxmox.yml
- hosts: proxmox
  gather_facts: yes
  remote_user: devops
  become: true

  pre_tasks:
    - name: Update apt-cache if needed
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - base_server
    - role: nfs_server
      tags: nfs
    - role: cloud_sync
      tags: cloudsync
  
  tasks:
    - name: Remove Proxmox Enterprise Repository
      lineinfile:
           dest=/etc/apt/sources.list.d/pve-enterprise.list
           regexp='^deb https://enterprise.proxmox.com/debian/pve'
           line="# deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise"
           state=present
           backup=yes
    - name: Add Proxmox No-Sub Repository
      lineinfile:
           dest=/etc/apt/sources.list.d/pve-enterprise.list
           line="deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription"
           state=present
           backup=yes
    - name: Add an Apt signing key, uses whichever key is at the URL
      ansible.builtin.apt_key:
        url: https://apt.grafana.com/gpg.key
        state: present
        keyring: /etc/apt/trusted.gpg.d/grafana.gpg
      tags: logging
    - name: Add Grafana Repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/trusted.gpg.d/grafana.gpg] https://apt.grafana.com stable main
        state: present
      tags: logging
    - name: Setup script directory
      ansible.builtin.file:
        path: "/home/{{ cloud_sources.rclone_user }}/bin"
        state: directory
        owner: "{{  cloud_sources.rclone_user }}"
        group: "{{  cloud_sources.rclone_user }}"
        mode: 0775
      tags: paperless,calibre
    - name: Paperless Consume Script
      ansible.builtin.template:
        src: templates/paperless_consume.sh.j2
        dest: "/home/{{ cloud_sources.rclone_user }}/bin/paperless_consume.sh"
        owner: "{{  cloud_sources.rclone_user }}"
        group: "{{  cloud_sources.rclone_user }}"
        mode : 0775
      tags: paperless
    - name: Paperless Consume Cron
      ansible.builtin.cron:
        name: "Download Files for Paperless"
        minute: "*/15"
        job: "/home/{{ cloud_sources.rclone_user }}/bin/paperless_consume.sh > /var/log/paperless 2>&1"
        user: "{{  cloud_sources.rclone_user }}"
      tags: paperless
    - name: Calibre Import Script
      ansible.builtin.template:
        src: templates/calibre_import.sh.j2
        dest: "/home/{{ cloud_sources.rclone_user }}/bin/calibre_import.sh"
        owner: "{{  cloud_sources.rclone_user }}"
        group: "{{  cloud_sources.rclone_user }}"
        mode : 0775
      tags: calibre
    - name: Calibre Import Cron
      ansible.builtin.cron:
        name: "Download Files for Calibre"
        minute: "*/5"
        job: "/home/{{ cloud_sources.rclone_user }}/bin/calibre_import.sh > /var/log/calibre 2>&1"
        user: "{{  cloud_sources.rclone_user }}"
      tags: calibre
    - name: Image Sync Script
      ansible.builtin.template:
        src: templates/image_sync.sh.j2
        dest: "/home/{{ cloud_sources.rclone_user }}/bin/image_sync.sh"
        owner: "{{  cloud_sources.rclone_user }}"
        group: "{{  cloud_sources.rclone_user }}"
        mode : 0775
      tags: imagesync
    - name: Image Sync Cron
      ansible.builtin.cron:
        name: "Image Sync"
        minute: "15"
        hour: "5"
        job: "/home/{{ cloud_sources.rclone_user }}/bin/image_sync.sh > /var/log/imagesync 2>&1"
        user: "{{  cloud_sources.rclone_user }}"
      tags: imagesync
    - name: Install promtail
      apt:
        name: promtail
        state: present
        update_cache: yes
      tags: logging
    - name: Setup Promtail Config
      ansible.builtin.template:
        src: templates/promtail-config.yml.j2
        dest: "/etc/promtail/config.yml"
      tags: logging
      notify: Restart Promtail
    - name: Install smartmontools
      apt:
        name: smartmontools
        state: present
        update_cache: yes
      tags: smart
    - name: Download scrutiny
      ansible.builtin.get_url:
        url: https://github.com/AnalogJ/scrutiny/releases/download/v0.7.2/scrutiny-collector-metrics-linux-amd64
        mode: 755
        dest: "/home/{{ cloud_sources.rclone_user }}/bin/scrutiny-collector-metrics-linux-amd64"
        owner: "{{  cloud_sources.rclone_user }}"
        group: "{{  cloud_sources.rclone_user }}"
      tags: smart
    - name: Setup config directory
      ansible.builtin.file:
        path: "/opt/scrutiny/config/"
        state: directory
        owner: "{{  cloud_sources.rclone_user }}"
        group: "{{  cloud_sources.rclone_user }}"
        mode: 0775
      tags: smart
    - name: Scrutiny config file
      ansible.builtin.template:
        src: templates/scrutiny_collector.yaml
        dest: "/opt/scrutiny/config/collector.yaml"
        owner: "{{  cloud_sources.rclone_user }}"
        group: "{{  cloud_sources.rclone_user }}"
        mode : 0664
      tags: smart
    - name: Scrutiny cron
      ansible.builtin.cron:
        name: "Scrutiny"
        hour: "0"
        minute: "15"
        job: "/home/{{ cloud_sources.rclone_user }}/bin/scrutiny-collector-metrics-linux-amd64 run > /var/log/scrutiny 2>&1"
        user: "root"
      tags: smart


  handlers:
  - name: Restart Promtail
    service:
      name=promtail
      state=restarted
