---
- name: Install Samba Server.
  apt:
    name: samba
    state: present
- name: Install WSDD (So computer shows on network)
  apt:
    name: wsdd-server
    state: present
- name: Setup Samba config
  ansible.builtin.template:
    src: templates/smb.conf.j2
    dest: "/etc/samba/smb.conf"
    owner: "root"
    group: "root"
    mode : 0644
- name: Setup WSDD config
  ansible.builtin.template:
    src: templates/wsdd.j2
    dest: "/etc/default/wsdd"
    owner: "root"
    group: "root"
    mode : 0644
